#!/bin/bash
# to run -> bash /pi/athma.pai-umw/analyses/jesse/KB/current_sci/module_scripts/mRNA_reorganizer_bygene.sh

# this script is meant to move mRNA .tsv's generated by the mRNA generator into the appropriate "bygene" directory, useful if supplementing datasets with additional substitution rate simulations

# Parent directory where the search will be performed - CHANGE AS NEEDED
parent_directory="/pi/athma.pai-umw/analyses/jesse/KB/current_sci/simulations/reads_200"

# Find directories starting with "5eUrates_" and store them in an array
directories=( "$parent_directory"/ENSG* )

# Loop through each directory
for directory in "${directories[@]}"; do
	# get the filepath for the "bygene" directory to move the .tsv's into
	new_directory=$(echo "$directory" | sed 's/simulations\/reads_200/simulations\/reads_200\/bygene/')
  if [ -d "$directory" ]; then
    find "$directory" -maxdepth 1 -type f -name "*.tsv" -exec mv {} "$new_directory" \;
  fi
done


# After completing this and checking it worked correctly, remove the gene directories in the parent directory with rm -r
